export enum EntityType {
    User = "User",
    ProfileImage = "ProfileImage",
    UserAdditionalEmails = "UserAdditionalEmails",
    PasswordRecoveryRequests = "PasswordRecoveryRequests",
    BlacklistedEmails = "BlacklistedEmails",
    Ticket = "Ticket",
    TicketPlaceholderImage = "TicketPlaceholderImage",
    Organizer = "Organizer",
    TicketTransaction = "TicketTransaction",
    Config = "Config",
    SessionLog = "SessionLog",
    UserActivityLog = "UserActivityLog",
    InvalidIdCheck = "InvalidIdCheck",
    ShoppingCart = "ShoppingCart",
    TicketAssignmentDeadline = "TicketAssignmentDeadline",
    SelfieImage = "SelfieImage",
    FAQ = "FAQ",
    UsersRegisteredVsUsersVerifiedPerYearReportResult = "UsersRegisteredVsUsersVerifiedPerYearReportResult",
    IncomingTicketsVsPersonalizedTicketsPerYearReportResult = "IncomingTicketsVsPersonalizedTicketsPerYearReportResult",
    IncomingTicketsPerOrganizerReportResult = "IncomingTicketsPerOrganizerReportResult",
    Event = "Event",
    OrganizerPlaceholderImage = "OrganizerPlaceholderImage",
    FAQUser = "FAQUser",
    SeatPlan = "SeatPlan",
    QRUrlParams = "QRUrlParams",
    CheckIn = "CheckIn"
}